version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - api
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 5555:5000
    volumes:
      - /app/node_modules
      - ./api:/app
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8888:8080
#Directory inside of Docker Desctop
volumes:
  mysql_data: